# Generated by Django 4.2.4 on 2023-08-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedcountry',
            name='date_of_visit',
            field=models.DateField(null=True),
        ),
    ]
