# Generated by Django 4.2.4 on 2023-08-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='home_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
